[package]
name = "fut-rs"
version = "0.1.0"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
edition = "2021"


[dependencies]
anyhow = "1"
futures = "0"
rand = "0"
tokio = { version = "1", features = ["full"] }
