[package]
name = "rbmq-rs"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
amqprs = { version = "1", features = ["traces"] }
anyhow = "1"
tokio = "1"
tracing = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
