[package]
name = "flight-rs"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-format = { version = "0", features = ["flight-data", "flight-service"] }
arrow2 = { version = "0", features = ["io_ipc", "io_parquet", "io_flight"] }
